### ISSUE TITLE
Replying to interpretations opens a new comment mentioning @UNKNOWN

### ISSUE THREAD

**Issue by nancyespinoza** [EyeSeeTea/interpretation-notification#11]

**Comment by nancyespinoza** [comment]
![Reply to interpretations open a new comment with automatic mentioning to the original author @username.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5be03ee8265f9b0012929fe8/125516c66e82c728ace21e0d46da918a2f9bc3bd80a9b64db058e2843b4333723d0dac2563c5ec38ba4c3b004f011beb510b0019a1acd76fb6f16534d24c5aa895320225826442bce5d741fb58e57ed211d2a6f8d55c84b06835b8c9d6186740544499ae1871f8c609d828b308b40f0bf54e6371fa64763e18ce4b2668796d34aeae8b03d3d734f1e8107d03c1e3e4fa1117f5288cc50e70714949e87b6ce15d07d02acd046a57f9b4ccf716490c1d03c9eacadfbbe9de386768.png)

**Comment by adrianq** [comment]
This is certainly a bug. We will have a look at it...
