### ISSUE TITLE
Post intepretation in PSI Wall

### ISSUE THREAD

**Issue by nancyespinoza** [EyeSeeTea/interpretation-notification#15]
I have notice there is not an option for creating a new interpretation, users are only able to comment (in the dboard, you can see an "add a new interpretation" label). Is this a logic/correct behavior?

**Comment by adrianq** [comment]
In my opinion, it makes sense but it is true that it could be controversial. In the dashboard, you are looking at a favourite/analytical object while in the interpretation app you are looking at interpretations. Create an interpretation from a favourite is correct however to create an interpretation from a interpretation doesn't make too much sense. Keep in mind that an interpretation can be different from its original favourite. The regular workflow for a user would be either to reuse an existing interpretation or go to the analytics tools/dashboard and create an interpretation from a favourite

**Comment by nancyespinoza** [comment]
ok, understood. It make sense now. Thank you.
