### ISSUE TITLE
User(s) mentioned in an interpretation should always receive a DHIS2 message

### ISSUE THREAD

**Issue by nancyespinoza** [EyeSeeTea/interpretation-notification#17]
According to https://docs.google.com/presentation/d/1chFXALpVkXr_otvYb9uCSNgYHDHHJYdU0DaFUX-wBjQ/edit#slide=id.g2565fc925b83c206_14
user must receive an email notification for a @mention even when email notifications are disable and OptOut @notifications is selected.

**Comment by adrianq** [comment]
@nancyespinoza This is not currently implemented now as it was not part of the functional requirements. Newsletter script only handles subscriptions and weekly digest. Therefore, if the user disables email notifications he will just receive an internal DHIS2 message
