### ISSUE TITLE
Event reports tables do not render on mail

### ISSUE THREAD

**Issue by nancyespinoza** [EyeSeeTea/interpretation-notification#18]
Event report tables on the DHIS2 Interpretation Digest are not shown. User only sees the interpretation or comment associated.

**Comment by nancyespinoza** [comment]
![Event reports render.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5be03ee8265f9b0012929fe8/125516c66e82c728ace21e0d46cd829f2d96c3bb8af9b051b04eb0862c4823763b46ef696097ec22ba416f43554d4bfe150d0b16a8acdb2bf4e335708a5c0ce885390b76c13c03b0aac04ee155e57dd205d0f4ae805ec1e03724e28f89473817071c8dfe5b3db2d4.PNG)

**Comment by adrianq** [comment]
We have double checked that visualization for event report is not actually supported by the DHIS2 API. See https://docs.dhis2.org/2.30/en/developer/html/dhis2_developer_manual_full.html#webapi_viewing_analytical_resource_representations

Closing this issue as it can not be implemented for now.
