### ISSUE TITLE
PT, ER, DV- charts and tables does not render on interpretation wall

### ISSUE THREAD

**Issue by nancyespinoza** [EyeSeeTea/interpretation-notification#2]
PT and DV: Charts and tables are able to be seen in their respective apps and dBoard. 

ER: Even though it is share with an specific user, Report is not shown in dBoard, interpretation wall or Event Reports app

**Comment by nancyespinoza** [comment]
![Charts and tables rendering.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5be03ee8265f9b0012929fe8/125516c66e82c728ace21e0d46cb9c9b319690e98ee7bb03b05cf2982c5567612c0aa72e628ced2ffd0e39111d0014f9121c4d4eeefcdb7ff3e26e24df0e0bbf84645f74c63a14f8ecd61db800a83c990dd4e8e8d51199a26867f5819d4e3914041d8dfe5535a09849cd5ffe4df300.png)

**Comment by adrianq** [comment]
It looks like a bug. Will investigate a bit more to understand where it is coming from
