### ISSUE TITLE
Hyperlink sent in emails does not work properly

### ISSUE THREAD

**Issue by nancyespinoza** [EyeSeeTea/interpretation-notification#4]
Unable to open link, wrong server in URL. 
For example: 

https://b670ffea.eu-west-1.psi.bao.systems/dhis-web-maps/index.html?id=TikCkbkklhI&interpretationid=IE1HjjAgvDr

**Comment by adrianq** [comment]
@nancyespinoza This is not an issue of the app. We use some internal DHIS2 instance settings (see below) to form the hyperlink sent as part of the email. As you can see, it is not properly set in leap. I will let @rodmelia know about it so they can fix the server.

![image](https://user-images.githubusercontent.com/6850223/48318494-9db06280-e5f9-11e8-9626-0349736da0ae.png)
