### ISSUE TITLE
User cannot unsubscribe from an email

### ISSUE THREAD

**Issue by nancyespinoza** [EyeSeeTea/interpretation-notification#5]
There is not "unsubscribe" button in the email text

**Comment by nancyespinoza** [comment]
![Unable to unsubscribe.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5be03ee8265f9b0012929fe8/125516c66e82c728ace21e0d46dd9a9b218e86e99be6ff56aa4ee5963a45357a2b01e1673295f127b54778154d555ca9130c0a10aeaddc79a6e469798a5c0bead4390b20c43a10bea4905dee5fee7fd616cfe3fe9846d2ea3d2fe68e8b4e361e051f89f65a37a08b06.png)

**Comment by adrianq** [comment]
This was not part of the requirements. Will talk to @rodmelia and, if needed, implement this feature as part of the next release

**Comment by adrianq** [comment]
This is finally implemented. The link at the bottom of the email  re-directs the user to the notification app
