### ISSUE TITLE
User is able to see an interpretation from dashboards not shared with him/her

### ISSUE THREAD

**Issue by nancyespinoza** [EyeSeeTea/interpretation-notification#6]
It does not matter what roles or OUs are assigned to him/her, the user is able to see the interpretation (not the chart or table) in the wall

**Comment by adrianq** [comment]
Sharing and permissions may not work as expected. There are a couple of PRs to the DHIS2 backend core that may change this behaviour. Will talk to @rodmelia and discuss with him if there is any plan to merge or reject those PRs
