### ISSUE TITLE
Sharing in Interpretation wall showing a UId

### ISSUE THREAD

**Issue by anamariaelsal** [EyeSeeTea/interpretation-notification#7]
When clicking on the Sharing button in the Interpretation wall, a UId is shown at the top of the pop-up screen. It should not be showing or should be replaced for a more understandable label

**Comment by nancyespinoza** [comment]
![Share interpretations.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5be03ee8265f9b0012929fe8/125516c66e82c728ace21e0d46db9c9b3187c3a081fdba51b44ff58028522e7c2717e1673295f127b54778154d555ca9130c0a10aeaddc79a6e469798a5c0bead4390b20c43a10bea4905dee5fee7fd616cfe3fe9846d2e93a2fe68e8b4d391d001e8cf85435a18b06.png)

**Comment by nancyespinoza** [comment]
Adrian, does the "share" button provides permission to the chart/table or just to the interpretation?

**Comment by adrianq** [comment]
@nancyespinoza this is the behaviour of the DHIS2 component. We are reusing the component you can also find in the new maps app:
![image](https://user-images.githubusercontent.com/6850223/49004669-ac039000-f15c-11e8-8cf5-ecb407b09990.png)

This component uses the displayname of the interpretation. See -> https://leap.psi-mis.org/api/interpretations/LjwAIAay2xI.json We can try to change it but it will take some time and will only work for PSI Interpretation app. For instance, we can maybe use the chart/table name plus the author of the interpretation or something along these lines...

The share button in the interpretation app changes permission for the interpretation itself. Actually, if you try to add a user or user group that is not part of the chart/table it will trigger a validation error
